version: '3.7'

services:

    web:
        build:
            target: dev
        ports:
        - "8080:80"

    app:
        build:
            target: dev
        volumes:
            - ~/.composer:/root/.composer:delegated
        environment:
            PHP_IDE_CONFIG: "serverName=app"

    node:
      build:
        context: .
        dockerfile: docker/node/Dockerfile
      volumes:
        - ./:/app:cached

    database:
        environment:
            MYSQL_ROOT_PASSWORD: laraform
        ports:
        - "42333:3306"
        restart: always
        volumes:
          - ./mysql-data:/var/lib/mysql:delegated
