version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: docker/web/web.dockerfile
      target: prod
    volumes:
      - ./public/:/app/public:cached
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: docker/app/app.dockerfile
      target: prod
    volumes:
      - ./:/app:cached
    depends_on:
      - database

  database:
    image: mysql:5.7

